// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client_proto/client.proto

/*
Package client_proto is a generated protocol buffer package.

It is generated from these files:
	client_proto/client.proto

It has these top-level messages:
	GetRequest
	DeleteRequest
	PutRequest
	GetResponse
	DeleteResponse
	PutResponse
*/
package client_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetResponse_Status int32

const (
	GetResponse_Success  GetResponse_Status = 0
	GetResponse_NotFound GetResponse_Status = 1
)

var GetResponse_Status_name = map[int32]string{
	0: "Success",
	1: "NotFound",
}
var GetResponse_Status_value = map[string]int32{
	"Success":  0,
	"NotFound": 1,
}

func (x GetResponse_Status) String() string {
	return proto.EnumName(GetResponse_Status_name, int32(x))
}
func (GetResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type DeleteResponse_Status int32

const (
	DeleteResponse_Success  DeleteResponse_Status = 0
	DeleteResponse_NotFound DeleteResponse_Status = 1
)

var DeleteResponse_Status_name = map[int32]string{
	0: "Success",
	1: "NotFound",
}
var DeleteResponse_Status_value = map[string]int32{
	"Success":  0,
	"NotFound": 1,
}

func (x DeleteResponse_Status) String() string {
	return proto.EnumName(DeleteResponse_Status_name, int32(x))
}
func (DeleteResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type PutResponse_Status int32

const (
	PutResponse_Success      PutResponse_Status = 0
	PutResponse_AlreadyExist PutResponse_Status = 1
)

var PutResponse_Status_name = map[int32]string{
	0: "Success",
	1: "AlreadyExist",
}
var PutResponse_Status_value = map[string]int32{
	"Success":      0,
	"AlreadyExist": 1,
}

func (x PutResponse_Status) String() string {
	return proto.EnumName(PutResponse_Status_name, int32(x))
}
func (PutResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type GetRequest struct {
	Key uint64 `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetRequest) GetKey() uint64 {
	if m != nil {
		return m.Key
	}
	return 0
}

type DeleteRequest struct {
	Key uint64 `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeleteRequest) GetKey() uint64 {
	if m != nil {
		return m.Key
	}
	return 0
}

type PutRequest struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PutRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetResponse struct {
	Value  string             `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	Status GetResponse_Status `protobuf:"varint,2,opt,name=status,enum=client_proto.GetResponse_Status" json:"status,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *GetResponse) GetStatus() GetResponse_Status {
	if m != nil {
		return m.Status
	}
	return GetResponse_Success
}

type DeleteResponse struct {
	Status DeleteResponse_Status `protobuf:"varint,1,opt,name=status,enum=client_proto.DeleteResponse_Status" json:"status,omitempty"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteResponse) GetStatus() DeleteResponse_Status {
	if m != nil {
		return m.Status
	}
	return DeleteResponse_Success
}

type PutResponse struct {
	Key    uint64             `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Status PutResponse_Status `protobuf:"varint,2,opt,name=status,enum=client_proto.PutResponse_Status" json:"status,omitempty"`
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PutResponse) GetKey() uint64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *PutResponse) GetStatus() PutResponse_Status {
	if m != nil {
		return m.Status
	}
	return PutResponse_Success
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "client_proto.GetRequest")
	proto.RegisterType((*DeleteRequest)(nil), "client_proto.DeleteRequest")
	proto.RegisterType((*PutRequest)(nil), "client_proto.PutRequest")
	proto.RegisterType((*GetResponse)(nil), "client_proto.GetResponse")
	proto.RegisterType((*DeleteResponse)(nil), "client_proto.DeleteResponse")
	proto.RegisterType((*PutResponse)(nil), "client_proto.PutResponse")
	proto.RegisterEnum("client_proto.GetResponse_Status", GetResponse_Status_name, GetResponse_Status_value)
	proto.RegisterEnum("client_proto.DeleteResponse_Status", DeleteResponse_Status_name, DeleteResponse_Status_value)
	proto.RegisterEnum("client_proto.PutResponse_Status", PutResponse_Status_name, PutResponse_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Node service

type NodeClient interface {
	ProcessGet(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	ProcessPut(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	ProcessDelete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) ProcessGet(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/client_proto.Node/ProcessGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) ProcessPut(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := grpc.Invoke(ctx, "/client_proto.Node/ProcessPut", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) ProcessDelete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := grpc.Invoke(ctx, "/client_proto.Node/ProcessDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Node service

type NodeServer interface {
	ProcessGet(context.Context, *GetRequest) (*GetResponse, error)
	ProcessPut(context.Context, *PutRequest) (*PutResponse, error)
	ProcessDelete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_ProcessGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).ProcessGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client_proto.Node/ProcessGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).ProcessGet(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_ProcessPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).ProcessPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client_proto.Node/ProcessPut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).ProcessPut(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_ProcessDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).ProcessDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client_proto.Node/ProcessDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).ProcessDelete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "client_proto.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessGet",
			Handler:    _Node_ProcessGet_Handler,
		},
		{
			MethodName: "ProcessPut",
			Handler:    _Node_ProcessPut_Handler,
		},
		{
			MethodName: "ProcessDelete",
			Handler:    _Node_ProcessDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client_proto/client.proto",
}

func init() { proto.RegisterFile("client_proto/client.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xcd, 0x4e, 0x83, 0x40,
	0x10, 0x66, 0xb5, 0xa2, 0x4e, 0x69, 0x43, 0x36, 0x1e, 0xa8, 0x1a, 0x83, 0xdb, 0x83, 0x3d, 0x61,
	0x52, 0x2f, 0x26, 0x9e, 0x8c, 0x3f, 0xbd, 0x98, 0x86, 0xd0, 0x07, 0x30, 0x08, 0x73, 0x68, 0x24,
	0x6c, 0x65, 0x77, 0x8d, 0xbd, 0xfa, 0xa0, 0x3e, 0x8b, 0x61, 0xc1, 0xba, 0x6d, 0xa9, 0x26, 0xbd,
	0x31, 0xc3, 0xc7, 0xf7, 0x37, 0x40, 0x2f, 0xc9, 0xa6, 0x98, 0xcb, 0xe7, 0x59, 0xc1, 0x25, 0xbf,
	0xac, 0x86, 0x40, 0x0f, 0xd4, 0x31, 0x5f, 0xb1, 0x33, 0x80, 0x11, 0xca, 0x08, 0xdf, 0x14, 0x0a,
	0x49, 0x5d, 0xd8, 0x7d, 0xc5, 0xb9, 0x47, 0x7c, 0x32, 0x68, 0x45, 0xe5, 0x23, 0x3b, 0x87, 0xce,
	0x3d, 0x66, 0x28, 0x71, 0x33, 0x84, 0x01, 0x84, 0x6a, 0x41, 0x71, 0x04, 0x7b, 0xef, 0x71, 0xa6,
	0x50, 0x23, 0x0e, 0xa3, 0x6a, 0x60, 0x9f, 0x04, 0xda, 0x5a, 0x47, 0xcc, 0x78, 0x2e, 0xb0, 0x19,
	0x45, 0xaf, 0xc1, 0x16, 0x32, 0x96, 0x4a, 0x78, 0x3b, 0x3e, 0x19, 0x74, 0x87, 0x7e, 0x60, 0x7a,
	0x0d, 0x0c, 0x82, 0x60, 0xa2, 0x71, 0x51, 0x8d, 0x67, 0x7d, 0xb0, 0xab, 0x0d, 0x6d, 0xc3, 0xfe,
	0x44, 0x25, 0x09, 0x0a, 0xe1, 0x5a, 0xd4, 0x81, 0x83, 0x31, 0x97, 0x8f, 0x5c, 0xe5, 0xa9, 0x4b,
	0x58, 0x01, 0xdd, 0x9f, 0x2c, 0xb5, 0x8d, 0x9b, 0x85, 0x20, 0xd1, 0x82, 0xfd, 0x65, 0xc1, 0x65,
	0xf4, 0x56, 0x9a, 0x65, 0x70, 0xdd, 0x4e, 0xad, 0xb8, 0x56, 0xdf, 0x7f, 0xa1, 0x8d, 0x8f, 0x57,
	0x0d, 0x5c, 0x34, 0x1b, 0x70, 0xc1, 0xb9, 0xcd, 0x0a, 0x8c, 0xd3, 0xf9, 0xc3, 0xc7, 0x54, 0x48,
	0x97, 0x0c, 0xbf, 0x08, 0xb4, 0xc6, 0x3c, 0x45, 0x7a, 0x07, 0x10, 0x16, 0xbc, 0xc4, 0x8d, 0x50,
	0x52, 0xaf, 0xa1, 0x5e, 0x7d, 0xc4, 0xe3, 0xde, 0xc6, 0xe2, 0x99, 0x65, 0x90, 0x84, 0x6a, 0x8d,
	0xe4, 0xf7, 0x4f, 0x58, 0x25, 0x31, 0x82, 0x30, 0x8b, 0x3e, 0x41, 0xa7, 0x26, 0xa9, 0x4a, 0xa6,
	0x27, 0xcd, 0xd5, 0x57, 0x54, 0xa7, 0x7f, 0xdd, 0x85, 0x59, 0x2f, 0xb6, 0xde, 0x5f, 0x7d, 0x07,
	0x00, 0x00, 0xff, 0xff, 0xc0, 0x9f, 0xed, 0x00, 0xf7, 0x02, 0x00, 0x00,
}
