language: go
go: 
 - 1.6
 - 1.7.x
 - release
 - tip

before_install:
  - sudo apt-get install protobuf-compiler
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - protoc --go_out=plugins=grpc:. DHT_proto/DHT.proto

script:
 - go test ./test/