language: go
go: 
 - 1.9.2

install:
  # download dependencies
  - cd ./server && go get
  - cd ../client && go get

script:
  - cd ../server && go build
  - cd ../client && go build
  - cd ../server && go test ./DHT_test
