language: go
go: 
 - 1.6
 - 1.7.x
 - release
 - tip

before_install:
  - curl -sL https://github.com/google/protobuf/releases/download/v3.5.0/protobuf-cpp-3.5.0.tar.gz | tar zx
  - cd protobuf-3.5.0
  - ./configure --prefix=/home/travis && make -j2 && make install
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - go get google.golang.org/grpc
  - protoc --go_out=plugins=grpc:. DHT_proto/DHT.proto

script:
 - go test ./test/